### ISSUE TITLE
`OSDictionary::iterateObjects` does not exist on 10.13.6 and lower

### ISSUE THREAD

**Issue by krinkuto11** [USBToolBox/kext#2]
After mapping from Windows, and including the UTBmap and USBToolbox in the EFI, I reboot and the ports that weren't working before RHUB fix aren't working again.

Just in case specs are:
B350M Mortar Arctic
Ryzen 5 1600
OpenCore 0.6.8
Mac OS X 10.13.6 High Sierra
Kext and USBTool are made with the latest release available

Also, mapping doesn't seem to be working at all.

**Comment by dhinakg** [comment]
I've fixed this in a new branch - can you please test [this](https://github.com/USBToolBox/kext/actions/runs/828497393) version of the kext? Just click "Artifacts" at the bottom

**Comment by krinkuto11** [comment]
[docs.zip](https://github.com/USBToolBox/kext/files/6453139/docs.zip)
Still doesn't seem to be working  (IOReg and OC included in the zip)

**Comment by dhinakg** [comment]
Alright, it turns out there aren't any block overloads for functions on High Sierra. I've rewritten my code to not use blocks - try [this version](https://github.com/USBToolBox/kext/actions/runs/832067005) of the kext. I've also made sure to adjust the OSBundleLibraries so there shouldn't be any more issues, although I can't install High Sierra right now so I can't test myself.

**Comment by krinkuto11** [comment]
Just tested it and it works! USBs mapped. In case you might need it, ill leave one last debug and IOReg with everything working as intended.
[Archivo comprimido.zip](https://github.com/USBToolBox/kext/files/6460137/Archivo.comprimido.zip)

**Comment by dhinakg** [comment]
Looks good, thank you! I will merge it in soon
